name: Show Build Tool Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  show-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Show Java version
        run: java -version

      - name: Show Maven version
        run: mvn -version

      - name: Show Gradle version
        run: gradle --version

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Parse Spring Boot version
        run: |
          if [ -f pom.xml ]; then
            PARENT_VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='parent']/*[local-name()='artifactId'][text()='spring-boot-starter-parent']/../*[local-name()='version']/text()" pom.xml 2>/dev/null || true)
            DEP_VERSION=$(xmllint --xpath "//*[local-name()='dependency'][*[local-name()='groupId']='org.springframework.boot']/*[local-name()='version']/text()" pom.xml 2>/dev/null | head -1 || true)
            PROP_VERSION=$(xmllint --xpath "/*[local-name()='project']/*[local-name()='properties']/*[local-name()='spring-boot.version']/text()" pom.xml 2>/dev/null || true)
            SPRING_BOOT_VERSION="${PARENT_VERSION:-${DEP_VERSION:-${PROP_VERSION}}}"
            echo "Spring Boot Version: $SPRING_BOOT_VERSION"
            echo "SPRING_BOOT_VERSION=$SPRING_BOOT_VERSION" >> $GITHUB_ENV
          elif [ -f build.gradle ]; then
            PLUGIN_VERSION=$(grep -E "id\(['\"]org.springframework.boot['\"]\).*version ['\"][0-9]+\.[0-9]+\.[0-9]+" build.gradle | grep -oE "[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+)?" | head -1)
            DEP_VERSION=$(grep -E "spring-boot.*:[0-9]+\.[0-9]+\.[0-9]+" build.gradle | grep -oE "[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9]+)?" | head -1)
            SPRING_BOOT_VERSION="${PLUGIN_VERSION:-${DEP_VERSION}}"
            echo "Spring Boot Version: $SPRING_BOOT_VERSION"
            echo "SPRING_BOOT_VERSION=$SPRING_BOOT_VERSION" >> $GITHUB_ENV
          else
            echo "No pom.xml or build.gradle found."
          fi

      - name: Collect version info
        run: |
          echo "Java Version:" > versions.txt
          java -version 2>&1 | head -n 1 >> versions.txt
          echo "" >> versions.txt

          echo "Maven Version:" >> versions.txt
          mvn -version 2>&1 | head -n 1 >> versions.txt
          echo "" >> versions.txt

          echo "Gradle Version:" >> versions.txt
          gradle --version 2>&1 | grep Gradle >> versions.txt
          echo "" >> versions.txt

          echo "Spring Boot Version: $SPRING_BOOT_VERSION" >> versions.txt

      - name: Upload versions.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-tool-versions
          path: versions.txt
